pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                print("Hello Worlld!")
                // Cloning repository
                git branch: 'main', url: 'https://github.com/Potterpurpp/potteraomfree.git'
            }
        }
         stage('Install Dependencies') {
            steps {
                # installs nvm (Node Version Manager)
                sh 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash'

                # download and install Node.js (you may need to restart the terminal)
                sh 'nvm install 20'

                # verifies the right Node.js version is in the environment
                sh 'node -v' 
                sh 'npm install'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build' // Runs the build command to compile TypeScript and generate production files
            }
        }

        stage('Test') {
            steps {
                echo 'Testing...'
                sh 'npm run test'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'

            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace...'
            cleanWs() // Cleans up the workspace after the build
        }
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}