pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                print("Hello Worlld!")
                // Cloning repository
                git branch: 'main', url: 'https://github.com/Potterpurpp/potteraomfree.git'
            }
        }
         stage('Install Dependencies') {
            steps {
                cd '/my-react-app'
                sh 'npm install'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build' // Runs the build command to compile TypeScript and generate production files
            }
        }

        stage('Test') {
            steps {
                echo 'Testing...'
                sh 'npm run test'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'

            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace...'
            cleanWs() // Cleans up the workspace after the build
        }
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}